version: '3.8'

services:
  ms2-mysql:
    image: mysql:8.0
    container_name: uce_trade_ms2_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uce_trade_ms2
    ports:
      - "3306:3306"
    volumes:
      - ms2_db_data:/var/lib/mysql

volumes:
  ms2_db_data: