server:
  port: ${SERVER_PORT:8085}

spring:
  application:
    name: ms6-payments
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3307/uce_trade_ms6}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}

stripe:
  secret-key: ${STRIPE_SECRET_KEY:}