package main

import (
	"log"
	
	"uce-trade-ms9/internal/adapters/input/rabbitmq"
	"uce-trade-ms9/internal/adapters/repositories/postgres"
	"uce-trade-ms9/internal/core/services"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	_ "uce-trade-ms9/docs" // This will be generated by swag init
)

// @title MS9 Analytics & Dashboards API
// @version 1.0
// @description REST API for Real-time Dashboards and Analytics in UCE Trade
// @host localhost:8000
// @BasePath /api/v1/analytics

func main() {
	log.Println("Starting MS9 Analytics & Dashboards...")

	// Normally this comes from env vars (e.g., os.Getenv("DATABASE_URL"))
	// For testing, we use a placeholder connection string. 
	// The real string will be configured in docker-compose later.
	dbURL := "postgres://postgres:postgres@localhost:5432/ms9_db?sslmode=disable"
	
	db, err := postgres.Connect(dbURL)
	if err != nil {
		log.Printf("Warning: Failed to connect to DB on startup: %v\n", err)
		log.Println("Continuing without DB for now (Wait for Docker setup in next tasks).")
	} else {
		defer db.Close()

		// Run pure SQL migrations
		if err := db.RunMigrations(); err != nil {
			log.Fatalf("Failed to run migrations: %v", err)
		}
	}

	// Setup Core Service
	var service *services.AnalyticsService
	if db != nil {
		service = services.NewAnalyticsService(db)
	}

	// Connect to RabbitMQ (Default port 5672 from your Docker setup)
	rabbitURL := "amqp://guest:guest@localhost:5672/"
	if service != nil {
		consumer, err := rabbitmq.NewConsumer(rabbitURL, service)
		if err != nil {
			log.Printf("Warning: Failed to connect to RabbitMQ on startup: %v", err)
		} else {
			defer consumer.Close()
			if err := consumer.StartConsuming(); err != nil {
				log.Printf("Warning: Failed to start consuming: %v", err)
			}
		}
	}

	// Initialize Gin Engine
	r := gin.Default()

	// Health check route
	// @Summary Health check
	// @Description check if MS9 is running
	// @Success 200 {object} map[string]string
	// @Router /health [get]
	r.GET("/api/v1/analytics/health", func(c *gin.Context) {
		c.JSON(200, gin.H{"status": "UP", "service": "ms9-analytics-dashboards"})
	})

	// Swagger documentation route
	r.GET("/api/v1/analytics/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Start the server
	port := "3009" // MS9 typically runs on 3009
	log.Printf("Server listening on port %s", port)
	if err := r.Run(":" + port); err != nil {
		log.Fatalf("Failed to start server: %v", err)
	}
}
