package main

import (
	"os"

	http_adapter "uce-trade-ms9/internal/adapters/input/http"
	"uce-trade-ms9/internal/adapters/input/rabbitmq"
	"uce-trade-ms9/internal/adapters/output/mqtt"
	"uce-trade-ms9/internal/adapters/repositories/postgres"
	"uce-trade-ms9/internal/core/services"

	"github.com/gin-gonic/gin"
	"github.com/sirupsen/logrus"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	_ "uce-trade-ms9/docs" // This will be generated by swag init
)

// @title MS9 Analytics & Dashboards API
// @version 1.0
// @description REST API for Real-time Dashboards and Analytics in UCE Trade
// @host localhost:8000
// @BasePath /api/v1/analytics

func main() {
	logrus.Info("Starting MS9 Analytics & Dashboards...")

	// Read DB URL: prefer DATABASE_URL, fall back to POSTGRES_URL (set by Terraform)
	dbURL := os.Getenv("DATABASE_URL")
	if dbURL == "" {
		dbURL = os.Getenv("POSTGRES_URL")
	}
	if dbURL == "" {
		dbURL = "postgres://postgres:root@localhost:5435/ms9_db?sslmode=disable"
	}

	db, err := postgres.Connect(dbURL)
	if err != nil {
		logrus.Errorf("Warning: Failed to connect to DB on startup: %v", err)
		logrus.Warn("Continuing without DB for now.")
	} else {
		defer db.Close()

		// Run pure SQL migrations
		if err := db.RunMigrations(); err != nil {
			logrus.Fatalf("Failed to run migrations: %v", err)
		}
	}

	// Setup MQTT Publisher — read from MQTT_BROKER or MQTT_URL env var
	mqttURL := "tcp://localhost:1883" // Default local fallback
	if envMqtt := os.Getenv("MQTT_BROKER"); envMqtt != "" {
		mqttURL = envMqtt
	} else if envMqtt := os.Getenv("MQTT_URL"); envMqtt != "" {
		mqttURL = envMqtt
	}
	publisher, err := mqtt.NewPublisher(mqttURL)
	if err != nil {
		logrus.Warnf("Warning: Failed to connect to MQTT on startup: %v", err)
	} else {
		defer publisher.Close()
	}

	// Setup Core Service
	var service *services.AnalyticsService
	if db != nil {
		service = services.NewAnalyticsService(db, publisher)
	}

	// Connect to RabbitMQ — read from RABBITMQ_URL env var (set by Terraform)
	rabbitURL := os.Getenv("RABBITMQ_URL")
	if rabbitURL == "" {
		rabbitURL = "amqp://guest:guest@localhost:5672/"
	}
	if service != nil {
		consumer, err := rabbitmq.NewConsumer(rabbitURL, service)
		if err != nil {
			logrus.Warnf("Warning: Failed to connect to RabbitMQ on startup: %v", err)
		} else {
			defer consumer.Close()
			if err := consumer.StartConsuming(); err != nil {
				logrus.Warnf("Warning: Failed to start consuming: %v", err)
			}
		}
	}

	// Setup HTTP Controller
	var controller *http_adapter.AnalyticsController
	if service != nil {
		controller = http_adapter.NewAnalyticsController(service)
	}

	// Initialize Gin Engine
	r := gin.Default()

	// REST Endpoints
	api := r.Group("/api/v1/analytics")
	{
		if controller != nil {
			api.GET("/admin", controller.GetAdminStats)
			api.GET("/student/:id", controller.GetStudentStats)
			api.GET("/student/:id/report", controller.DownloadStudentReport)
		}
	}

	// Health check route
	// @Summary Health check
	// @Description check if MS9 is running
	// @Success 200 {object} map[string]string
	// @Router /health [get]
	r.GET("/api/v1/analytics/health", func(c *gin.Context) {
		c.JSON(200, gin.H{"status": "UP", "service": "ms9-analytics-dashboards"})
	})

	// Swagger documentation route
	r.GET("/api/v1/analytics/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Start the server
	port := os.Getenv("PORT")
	if port == "" {
		port = "3009"
	}
	logrus.Infof("Server listening on port %s", port)
	if err := r.Run(":" + port); err != nil {
		logrus.Fatalf("Failed to start server: %v", err)
	}
}
